// Kannada Vowels
// 'sound' = what TTS speaks to approximate the actual Kannada letter sound
export const vowels = [
  { letter: 'ಅ', phonetic: 'a', sound: 'u', example: 'ಅಮ್ಮ', meaning: 'Mother' },
  { letter: 'ಆ', phonetic: 'aa', sound: 'aa', example: 'ಆನೆ', meaning: 'Elephant' },
  { letter: 'ಇ', phonetic: 'e', sound: 'ih', example: 'ಇಲಿ', meaning: 'Mouse' },
  { letter: 'ಈ', phonetic: 'ee', sound: 'ee', example: 'ಈಗ', meaning: 'Now' },
  { letter: 'ಉ', phonetic: 'u', sound: 'oo', example: 'ಉಪ್ಪು', meaning: 'Salt' },
  { letter: 'ಊ', phonetic: 'uu', sound: 'ooh', example: 'ಊಟ', meaning: 'Meal' },
  { letter: 'ಋ', phonetic: 'ru', sound: 'ruh', example: 'ಋಷಿ', meaning: 'Sage' },
  { letter: 'ಎ', phonetic: 'ae', sound: 'eh', example: 'ಎಲೆ', meaning: 'Leaf' },
  { letter: 'ಏ', phonetic: 'ay', sound: 'ay', example: 'ಏನು', meaning: 'What' },
  { letter: 'ಐ', phonetic: 'ai', sound: 'eye', example: 'ಐದು', meaning: 'Five' },
  { letter: 'ಒ', phonetic: 'o', sound: 'oh', example: 'ಒಂದು', meaning: 'One' },
  { letter: 'ಓ', phonetic: 'oo', sound: 'oa', example: 'ಓದು', meaning: 'Read' },
  { letter: 'ಔ', phonetic: 'au', sound: 'ow', example: 'ಔಷಧಿ', meaning: 'Medicine' },
  { letter: 'ಅಂ', phonetic: 'am', sound: 'um', example: 'ಅಂಗಡಿ', meaning: 'Shop' },
  { letter: 'ಅಃ', phonetic: 'aha', sound: 'aha', example: 'ದುಃಖ', meaning: 'Sorrow' },
];

// Kannada Consonants
// 'sound' = what TTS speaks to approximate the actual Kannada letter sound
export const consonants = [
  { letter: 'ಕ', phonetic: 'ka', sound: 'kuh', example: 'ಕಮಲ', meaning: 'Lotus' },
  { letter: 'ಖ', phonetic: 'kha', sound: 'khuh', example: 'ಖಡ್ಗ', meaning: 'Sword' },
  { letter: 'ಗ', phonetic: 'ga', sound: 'guh', example: 'ಗಣೇಶ', meaning: 'Ganesha' },
  { letter: 'ಘ', phonetic: 'gha', sound: 'ghuh', example: 'ಘಂಟೆ', meaning: 'Bell' },
  { letter: 'ಙ', phonetic: 'nga', sound: 'nguh', example: 'ಅಂಗ', meaning: 'Body part' },
  { letter: 'ಚ', phonetic: 'cha', sound: 'chuh', example: 'ಚಂದ್ರ', meaning: 'Moon' },
  { letter: 'ಛ', phonetic: 'chha', sound: 'chhuh', example: 'ಛತ್ರಿ', meaning: 'Umbrella' },
  { letter: 'ಜ', phonetic: 'ja', sound: 'juh', example: 'ಜಲ', meaning: 'Water' },
  { letter: 'ಝ', phonetic: 'jha', sound: 'jhuh', example: 'ಝರಿ', meaning: 'Stream' },
  { letter: 'ಞ', phonetic: 'nya', sound: 'nyuh', example: 'ಜ್ಞಾನ', meaning: 'Knowledge' },
  { letter: 'ಟ', phonetic: 'ta', sound: 'tuh', example: 'ಟೊಮ್ಯಾಟೋ', meaning: 'Tomato' },
  { letter: 'ಠ', phonetic: 'tha', sound: 'thuh', example: 'ಠಕ್ಕ', meaning: 'Cheat' },
  { letter: 'ಡ', phonetic: 'da', sound: 'duh', example: 'ಡಮರು', meaning: 'Drum' },
  { letter: 'ಢ', phonetic: 'dha', sound: 'dhuh', example: 'ಢಾಲು', meaning: 'Shield' },
  { letter: 'ಣ', phonetic: 'na', sound: 'nuh', example: 'ಗುಣ', meaning: 'Quality' },
  { letter: 'ತ', phonetic: 'tha', sound: 'thuh', example: 'ತಂದೆ', meaning: 'Father' },
  { letter: 'ಥ', phonetic: 'thha', sound: 'thhuh', example: 'ಸ್ನಾನ', meaning: 'Bath' },
  { letter: 'ದ', phonetic: 'da', sound: 'dhuh', example: 'ದೀಪ', meaning: 'Lamp' },
  { letter: 'ಧ', phonetic: 'dha', sound: 'dhuh', example: 'ಧನ', meaning: 'Wealth' },
  { letter: 'ನ', phonetic: 'na', sound: 'nuh', example: 'ನದಿ', meaning: 'River' },
  { letter: 'ಪ', phonetic: 'pa', sound: 'puh', example: 'ಪುಸ್ತಕ', meaning: 'Book' },
  { letter: 'ಫ', phonetic: 'pha', sound: 'phuh', example: 'ಫಲ', meaning: 'Fruit' },
  { letter: 'ಬ', phonetic: 'ba', sound: 'buh', example: 'ಬೆಕ್ಕು', meaning: 'Cat' },
  { letter: 'ಭ', phonetic: 'bha', sound: 'bhuh', example: 'ಭೂಮಿ', meaning: 'Earth' },
  { letter: 'ಮ', phonetic: 'ma', sound: 'muh', example: 'ಮನೆ', meaning: 'House' },
  { letter: 'ಯ', phonetic: 'ya', sound: 'yuh', example: 'ಯಂತ್ರ', meaning: 'Machine' },
  { letter: 'ರ', phonetic: 'ra', sound: 'ruh', example: 'ರಾಜ', meaning: 'King' },
  { letter: 'ಲ', phonetic: 'la', sound: 'luh', example: 'ಲತಾ', meaning: 'Vine' },
  { letter: 'ವ', phonetic: 'va', sound: 'vuh', example: 'ವನ', meaning: 'Forest' },
  { letter: 'ಶ', phonetic: 'sha', sound: 'shuh', example: 'ಶಾಲೆ', meaning: 'School' },
  { letter: 'ಷ', phonetic: 'sha', sound: 'shuh', example: 'ಷಟ್', meaning: 'Six' },
  { letter: 'ಸ', phonetic: 'sa', sound: 'suh', example: 'ಸೂರ್ಯ', meaning: 'Sun' },
  { letter: 'ಹ', phonetic: 'ha', sound: 'huh', example: 'ಹಕ್ಕಿ', meaning: 'Bird' },
  { letter: 'ಳ', phonetic: 'la', sound: 'luh', example: 'ಹಳೆ', meaning: 'Old' },
];

// Common Phrases
export const phrases = [
  { kannada: 'ನಮಸ್ಕಾರ', phonetic: 'Namaskaara', english: 'Hello', context: 'Used as a universal greeting, suitable for all ages and settings.' },
  { kannada: 'ಧನ್ಯವಾದ', phonetic: 'Dhanyavaada', english: 'Thank you', context: 'Used to express gratitude in formal and informal settings.' },
  { kannada: 'ದಯವಿಟ್ಟು', phonetic: 'Dayavittu', english: 'Please', context: 'Added before requests to sound polite and respectful.' },
  { kannada: 'ಹೌದು', phonetic: 'Haudu', english: 'Yes', context: 'Simple affirmation, used in daily conversations.' },
  { kannada: 'ಇಲ್ಲ', phonetic: 'Illa', english: 'No', context: 'Polite negation, used commonly in all contexts.' },
  { kannada: 'ನನ್ನ ಹೆಸರು...', phonetic: 'Nanna hesaru...', english: 'My name is...', context: 'Used when introducing yourself to someone new.' },
  { kannada: 'ನಿಮ್ಮ ಹೆಸರೇನು?', phonetic: 'Nimma hesarenu?', english: "What's your name?", context: 'Polite way to ask someone their name.' },
  { kannada: 'ಕುಶಲವಾಗಿದ್ದೀರಾ?', phonetic: 'Kushalvaagiddeeraa?', english: 'How are you?', context: 'Common greeting, often used after initial hello.' },
  { kannada: 'ನಾನು ಸುಖವಾಗಿದ್ದೇನೆ', phonetic: 'Naanu sukhavaagiddene', english: "I'm well", context: 'Response to "How are you?" in a positive manner.' },
  { kannada: 'ಎಷ್ಟು ಬೆಲೆ?', phonetic: 'Eshtu bele?', english: 'How much does it cost?', context: 'Essential phrase for shopping at markets and stores.' },
  { kannada: 'ಶೌಚಾಲಯ ಎಲ್ಲಿ?', phonetic: 'Shauchalaya elli?', english: 'Where is the toilet?', context: 'Useful when visiting new places or traveling.' },
  { kannada: 'ನನಗೆ ಸಹಾಯ ಮಾಡಿ', phonetic: 'Nanage sahaaya maadi', english: 'Help me', context: 'Used in emergencies or when you need assistance.' },
  { kannada: 'ನೀರು ಕೊಡಿ', phonetic: 'Neeru kodi', english: 'Give me water', context: 'Used in restaurants or when visiting someone\'s home.' },
  { kannada: 'ಹೋಗಿ ಬರುತ್ತೇನೆ', phonetic: 'Hogi baruttene', english: 'I will go and come back (Goodbye)', context: 'Common farewell phrase, implies you\'ll return.' },
  { kannada: 'ಶುಭ ದಿನ', phonetic: 'Shubha dina', english: 'Good day', context: 'Used to wish someone a good day.' },
];

// Reading exercises
export const readingExercises = [
  {
    level: 1,
    label: 'Beginner',
    exercises: [
      { kannada: 'ನನ್ನ ಪುಸ್ತಕ', phonetic: 'Nanna pustaka', english: 'My book' },
      { kannada: 'ದೊಡ್ಡ ಮನೆ', phonetic: 'Dodda mane', english: 'Big house' },
      { kannada: 'ಒಳ್ಳೆಯ ಹುಡುಗ', phonetic: 'Olleya huduga', english: 'Good boy' },
      { kannada: 'ಬಿಸಿ ನೀರು', phonetic: 'Bisi neeru', english: 'Hot water' },
      { kannada: 'ಹಸಿರು ಮರ', phonetic: 'Hasiru mara', english: 'Green tree' },
    ],
  },
  {
    level: 2,
    label: 'Intermediate',
    exercises: [
      { kannada: 'ನನ್ನ ಪುಸ್ತಕ ಎಲ್ಲಿ?', phonetic: 'Nanna pustaka elli?', english: 'Where is my book?' },
      { kannada: 'ನಾನು ಶಾಲೆಗೆ ಹೋಗುತ್ತೇನೆ', phonetic: 'Naanu shaalege hoguttene', english: 'I go to school' },
      { kannada: 'ಅವರು ಮನೆಯಲ್ಲಿ ಇದ್ದಾರೆ', phonetic: 'Avaru maneyalli iddare', english: 'They are at home' },
      { kannada: 'ಈ ಹಣ್ಣು ತುಂಬಾ ಸಿಹಿ', phonetic: 'Ee hannu tumba sihi', english: 'This fruit is very sweet' },
    ],
  },
  {
    level: 3,
    label: 'Advanced',
    exercises: [
      { kannada: 'ನಾನು ಪ್ರತಿ ದಿನ ಬೆಳಿಗ್ಗೆ ಓಡುತ್ತೇನೆ', phonetic: 'Naanu prati dina beliggé oduttene', english: 'I run every morning' },
      { kannada: 'ಅವಳು ಸುಂದರವಾದ ಚಿತ್ರ ಬರೆದಳು', phonetic: 'Avalu sundaravaada chitra baredalu', english: 'She drew a beautiful picture' },
      { kannada: 'ಈ ಊರಿನಲ್ಲಿ ಒಂದು ದೊಡ್ಡ ದೇವಸ್ಥಾನ ಇದೆ', phonetic: 'Ee oorinalli ondu dodda devasthaana ide', english: 'There is a big temple in this town' },
    ],
  },
];

// All quiz scenario sets — one is randomly picked per session
// Each set has i18n fields: title_hi, subtitle_hi, ctaLabel_hi, and scenarios with title_hi/prompt_hi/feedback_hi per option

export const allQuizSets = [
  {
    id: 'market',
    title: 'The Grand Bazaar',
    title_hi: 'महा बाज़ार',
    kannadaTitle: 'ದೊಡ್ಡ ಮಾರುಕಟ್ಟೆ',
    subtitle: 'Test your Kannada skills in a realistic market scenario. Navigate conversations with shopkeepers, negotiate prices, and find your way around.',
    subtitle_hi: 'एक वास्तविक बाज़ार परिदृश्य में अपनी कन्नड़ कौशल का परीक्षण करें। दुकानदारों से बातचीत करें, कीमतें तय करें और रास्ता खोजें।',
    image: 'https://media.base44.com/images/public/69e0ad6ff5507c1eca24e4d4/209b6b353_generated_55967778.png',
    imageAlt: 'Traditional Indian market bazaar',
    ctaLabel: 'Enter the Market',
    ctaLabel_hi: 'बाज़ार में जाएं',
    scenarios: [
      {
        id: 1,
        title: 'Greeting the Shopkeeper',
        title_hi: 'दुकानदार को अभिवादन',
        prompt: 'You enter a market. Greet the shopkeeper politely.',
        prompt_hi: 'आप एक बाज़ार में प्रवेश करते हैं। दुकानदार को विनम्रता से अभिवादन करें।',
        options: [
          { text: 'ಹೋಗಿ ಬರುತ್ತೇನೆ', phonetic: 'Hogi baruttene', correct: false, feedback: 'This means "goodbye" — not quite right for a greeting!', feedback_hi: 'इसका अर्थ है "अलविदा" — अभिवादन के लिए सही नहीं है!' },
          { text: 'ಎಷ್ಟು ಬೆಲೆ?', phonetic: 'Eshtu bele?', correct: false, feedback: 'This means "How much?" — save it for later!', feedback_hi: 'इसका अर्थ है "कितना?" — इसे बाद के लिए रखें!' },
          { text: 'ನಮಸ್ಕಾರ', phonetic: 'Namaskaara', correct: true, feedback: 'Perfect! A warm and respectful greeting.', feedback_hi: 'बिल्कुल सही! एक गर्म और सम्मानजनक अभिवादन।' },
        ],
      },
      {
        id: 2,
        title: 'Asking for a Product',
        title_hi: 'उत्पाद माँगना',
        prompt: 'You want to buy tomatoes. Ask the shopkeeper for them.',
        prompt_hi: 'आप टमाटर खरीदना चाहते हैं। दुकानदार से माँगें।',
        options: [
          { text: 'ನೀರು ಕೊಡಿ', phonetic: 'Neeru kodi', correct: false, feedback: 'This asks for water, not tomatoes!', feedback_hi: 'यह पानी के लिए पूछ रहा है, टमाटर के लिए नहीं!' },
          { text: 'ಟೊಮ್ಯಾಟೋ ಕೊಡಿ', phonetic: 'Tomato kodi', correct: true, feedback: 'Great! Clear and direct request.', feedback_hi: 'बढ़िया! स्पष्ट और सीधी माँग।' },
          { text: 'ಧನ್ಯವಾದ', phonetic: 'Dhanyavaada', correct: false, feedback: 'This means "Thank you" — you haven\'t bought anything yet!', feedback_hi: 'इसका अर्थ है "धन्यवाद" — आपने अभी कुछ खरीदा नहीं है!' },
        ],
      },
      {
        id: 3,
        title: 'Negotiating the Price',
        title_hi: 'कीमत तय करना',
        prompt: 'The shopkeeper says tomatoes are ₹50/kg. Ask the price and try to negotiate.',
        prompt_hi: 'दुकानदार कहता है टमाटर ₹50/किग्रा हैं। कीमत पूछें और मोलभाव करें।',
        options: [
          { text: 'ಇಲ್ಲ ಬೇಡ', phonetic: 'Illa beda', correct: false, feedback: 'This means "No, I don\'t want" — a bit abrupt for negotiation!', feedback_hi: 'इसका अर्थ है "नहीं, मुझे नहीं चाहिए" — मोलभाव के लिए थोड़ा अशिष्ट है!' },
          { text: 'ನನಗೆ ಗೊತ್ತಿಲ್ಲ', phonetic: 'Nanage gottilla', correct: false, feedback: 'This means "I don\'t know" — not helpful for negotiating!', feedback_hi: 'इसका अर्थ है "मुझे नहीं पता" — मोलभाव के लिए उपयोगी नहीं!' },
          { text: 'ಎಷ್ಟು ಬೆಲೆ? ಸ್ವಲ್ಪ ಕಡಿಮೆ ಮಾಡಿ', phonetic: 'Eshtu bele? Swalpa kadime maadi', correct: true, feedback: 'Excellent! You asked the price and politely negotiated.', feedback_hi: 'शानदार! आपने कीमत पूछी और विनम्रता से मोलभाव किया।' },
        ],
      },
      {
        id: 4,
        title: 'Asking for Directions',
        title_hi: 'रास्ता पूछना',
        prompt: 'You need to find the fruit stall. Ask where it is.',
        prompt_hi: 'आपको फल की दुकान ढूँढनी है। पूछें कि वह कहाँ है।',
        options: [
          { text: 'ಹಣ್ಣಿನ ಅಂಗಡಿ ಎಲ್ಲಿ?', phonetic: 'Hannina angadi elli?', correct: true, feedback: 'Perfect question formation! "Where is the fruit shop?"', feedback_hi: 'बिल्कुल सही प्रश्न! "फल की दुकान कहाँ है?"' },
          { text: 'ನನ್ನ ಹೆಸರು...', phonetic: 'Nanna hesaru...', correct: false, feedback: 'This introduces yourself — not what we need right now!', feedback_hi: 'यह खुद का परिचय देता है — अभी हमें यह नहीं चाहिए!' },
          { text: 'ಶುಭ ದಿನ', phonetic: 'Shubha dina', correct: false, feedback: 'This means "Good day" — polite but not a direction question!', feedback_hi: 'इसका अर्थ है "शुभ दिन" — विनम्र है पर रास्ते का सवाल नहीं!' },
        ],
      },
      {
        id: 5,
        title: 'Thanking & Farewell',
        title_hi: 'धन्यवाद और विदाई',
        prompt: 'You\'ve completed your shopping. Thank the shopkeeper and say goodbye.',
        prompt_hi: 'आपकी खरीदारी पूरी हो गई। दुकानदार को धन्यवाद दें और अलविदा कहें।',
        options: [
          { text: 'ಎಷ್ಟು ಬೆಲೆ?', phonetic: 'Eshtu bele?', correct: false, feedback: 'You\'re asking the price again — you\'ve already finished!', feedback_hi: 'आप फिर से कीमत पूछ रहे हैं — आप पहले ही खरीद चुके हैं!' },
          { text: 'ಧನ್ಯವಾದ, ನಮಸ್ಕಾರ', phonetic: 'Dhanyavaada, Namaskaara', correct: true, feedback: 'Culturally appropriate! Thank you and a respectful farewell.', feedback_hi: 'सांस्कृतिक रूप से उपयुक्त! धन्यवाद और सम्मानजनक विदाई।' },
          { text: 'ನನಗೆ ಸಹಾಯ ಮಾಡಿ', phonetic: 'Nanage sahaaya maadi', correct: false, feedback: 'This asks for help — not quite a goodbye!', feedback_hi: 'यह मदद माँगता है — यह अलविदा नहीं है!' },
        ],
      },
      {
        id: 6,
        title: 'Handling Unavailability',
        title_hi: 'अनुपलब्धता से निपटना',
        prompt: 'The shopkeeper says the product you want isn\'t available. Respond appropriately.',
        prompt_hi: 'दुकानदार कहता है जो आप चाहते हैं वह उपलब्ध नहीं है। उचित जवाब दें।',
        options: [
          { text: 'ಇಲ್ಲ!', phonetic: 'Illa!', correct: false, feedback: 'Just saying "No!" is a bit rude in this context.', feedback_hi: 'केवल "नहीं!" कहना इस संदर्भ में थोड़ा अशिष्ट है।' },
          { text: 'ನಾನು ಹೋಗುತ್ತೇನೆ', phonetic: 'Naanu hoguttene', correct: false, feedback: 'Walking away works, but it\'s not the most communicative response!', feedback_hi: 'चले जाना काम करता है, लेकिन यह सबसे अच्छा जवाब नहीं है!' },
          { text: 'ಸರಿ, ಬೇರೆ ಏನಾದರೂ ಇದೆಯೇ?', phonetic: 'Sari, bere enaadaru ideye?', correct: true, feedback: 'Great problem-solving! You accepted and asked for alternatives.', feedback_hi: 'बढ़िया! आपने स्वीकार किया और विकल्प पूछे।' },
        ],
      },
    ],
  },
  {
    id: 'restaurant',
    title: 'At the Restaurant',
    title_hi: 'रेस्तरां में',
    kannadaTitle: 'ಹೋಟೆಲ್‌ನಲ್ಲಿ',
    subtitle: 'Practice ordering food, asking for the menu, and wrapping up your meal at a local Kannada restaurant.',
    subtitle_hi: 'एक स्थानीय कन्नड़ रेस्तरां में खाना ऑर्डर करना, मेनू माँगना और खाना खत्म करने का अभ्यास करें।',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
    imageAlt: 'Indian restaurant interior',
    ctaLabel: 'Enter the Restaurant',
    ctaLabel_hi: 'रेस्तरां में जाएं',
    scenarios: [
      {
        id: 1,
        title: 'Asking for the Menu',
        title_hi: 'मेनू माँगना',
        prompt: 'You sit down at a restaurant. Ask the waiter for the menu.',
        prompt_hi: 'आप रेस्तरां में बैठते हैं। वेटर से मेनू माँगें।',
        options: [
          { text: 'ಊಟ ರೆಡಿ ಇದೆಯೇ?', phonetic: 'Oota ready ideye?', correct: false, feedback: 'This asks if food is ready — first ask to see the menu!', feedback_hi: 'यह पूछता है कि खाना तैयार है — पहले मेनू देखने को माँगें!' },
          { text: 'ಮೆನು ತೋರಿಸಿ', phonetic: 'Menu toorisi', correct: true, feedback: 'Perfect! Politely asking to show the menu.', feedback_hi: 'बिल्कुल सही! विनम्रता से मेनू दिखाने को कह रहे हैं।' },
          { text: 'ಬಿಲ್ ತನ್ನಿ', phonetic: 'Bill tanni', correct: false, feedback: 'The bill comes at the end — you haven\'t ordered yet!', feedback_hi: 'बिल अंत में आता है — आपने अभी ऑर्डर नहीं दिया!' },
        ],
      },
      {
        id: 2,
        title: 'Ordering Food',
        title_hi: 'खाना ऑर्डर करना',
        prompt: 'You want to order rice and sambar. How do you ask?',
        prompt_hi: 'आप चावल और सांबर ऑर्डर करना चाहते हैं। कैसे पूछेंगे?',
        options: [
          { text: 'ಇನ್ನೂ ಬೇಡ', phonetic: 'Innu beda', correct: false, feedback: 'This means "not yet / don\'t want more" — try ordering instead!', feedback_hi: 'इसका अर्थ है "अभी नहीं / और नहीं चाहिए" — इसके बजाय ऑर्डर करें!' },
          { text: 'ನನಗೆ ಅನ್ನ ಮತ್ತು ಸಾಂಬಾರ್ ಕೊಡಿ', phonetic: 'Nanage anna mattu saambaar kodi', correct: true, feedback: 'Excellent! Clear and polite order.', feedback_hi: 'शानदार! स्पष्ट और विनम्र ऑर्डर।' },
          { text: 'ಊಟ ಚೆನ್ನಾಗಿದೆ', phonetic: 'Oota chennaagide', correct: false, feedback: 'This means "the food is good" — you haven\'t tasted it yet!', feedback_hi: 'इसका अर्थ है "खाना अच्छा है" — आपने अभी चखा नहीं!' },
        ],
      },
      {
        id: 3,
        title: 'Asking for Water',
        title_hi: 'पानी माँगना',
        prompt: 'Your glass is empty. Ask the waiter for water.',
        prompt_hi: 'आपका गिलास खाली है। वेटर से पानी माँगें।',
        options: [
          { text: 'ನೀರು ಕೊಡಿ', phonetic: 'Neeru kodi', correct: true, feedback: 'Simple and correct — "Give me water."', feedback_hi: 'सरल और सही — "मुझे पानी दें।"' },
          { text: 'ತಿಂಡಿ ಕೊಡಿ', phonetic: 'Tindi kodi', correct: false, feedback: 'This asks for snacks, not water!', feedback_hi: 'यह नाश्ते के लिए पूछ रहा है, पानी के लिए नहीं!' },
          { text: 'ಮತ್ತೆ ಬರುತ್ತೇನೆ', phonetic: 'Matte baruttene', correct: false, feedback: 'This means "I\'ll come again" — a bit out of place here!', feedback_hi: 'इसका अर्थ है "मैं फिर आऊँगा" — यहाँ थोड़ा बेमेल है!' },
        ],
      },
      {
        id: 4,
        title: 'Complimenting the Food',
        title_hi: 'खाने की तारीफ करना',
        prompt: 'The food was delicious. Tell the waiter!',
        prompt_hi: 'खाना स्वादिष्ट था। वेटर को बताएं!',
        options: [
          { text: 'ಊಟ ರುಚಿಯಾಗಿತ್ತು', phonetic: 'Oota ruchiyaagittu', correct: true, feedback: 'Wonderful! "The food was tasty" — they\'ll love to hear it.', feedback_hi: 'शानदार! "खाना स्वादिष्ट था" — उन्हें यह सुनकर खुशी होगी।' },
          { text: 'ಇನ್ನೂ ಕೊಡಿ', phonetic: 'Innu kodi', correct: false, feedback: 'This asks for more food — close, but doesn\'t express the compliment!', feedback_hi: 'यह और खाना माँगता है — करीब है, लेकिन तारीफ नहीं!' },
          { text: 'ತಡ ಆಯಿತು', phonetic: 'Tada aayitu', correct: false, feedback: 'This means "it was late" — not a compliment!', feedback_hi: 'इसका अर्थ है "देर हो गई" — यह तारीफ नहीं है!' },
        ],
      },
      {
        id: 5,
        title: 'Asking for the Bill',
        title_hi: 'बिल माँगना',
        prompt: 'You\'re done eating. Ask for the bill.',
        prompt_hi: 'आपका खाना खत्म हो गया। बिल माँगें।',
        options: [
          { text: 'ಇನ್ನೂ ಏನು ಇದೆ?', phonetic: 'Innu enu ide?', correct: false, feedback: 'This asks what else is available — you\'re done eating!', feedback_hi: 'यह पूछता है और क्या उपलब्ध है — आप खाना खत्म कर चुके हैं!' },
          { text: 'ಧನ್ಯವಾದ', phonetic: 'Dhanyavaada', correct: false, feedback: 'Gratitude is great, but you still need to ask for the bill!', feedback_hi: 'कृतज्ञता अच्छी है, लेकिन आपको अभी भी बिल माँगना है!' },
          { text: 'ಬಿಲ್ ತನ್ನಿ', phonetic: 'Bill tanni', correct: true, feedback: 'Correct! "Bring the bill" — short and clear.', feedback_hi: 'सही! "बिल लाओ" — छोटा और स्पष्ट।' },
        ],
      },
    ],
  },
  {
    id: 'bus',
    title: 'The Bus Journey',
    title_hi: 'बस की यात्रा',
    kannadaTitle: 'ಬಸ್ ಪ್ರಯಾಣ',
    subtitle: 'Navigate a city bus ride — buy a ticket, ask the conductor about stops, and find your way to your destination.',
    subtitle_hi: 'शहर की बस यात्रा करें — टिकट खरीदें, कंडक्टर से स्टॉप के बारे में पूछें और अपने गंतव्य तक पहुँचें।',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&q=80',
    imageAlt: 'Indian city bus',
    ctaLabel: 'Board the Bus',
    ctaLabel_hi: 'बस में चढ़ें',
    scenarios: [
      {
        id: 1,
        title: 'Boarding the Bus',
        title_hi: 'बस में चढ़ना',
        prompt: 'You\'re at the bus stop. Ask if this bus goes to the railway station.',
        prompt_hi: 'आप बस स्टॉप पर हैं। पूछें कि क्या यह बस रेलवे स्टेशन जाती है।',
        options: [
          { text: 'ಈ ಬಸ್ ರೈಲ್ವೇ ಸ್ಟೇಶನ್‌ಗೆ ಹೋಗುತ್ತದೆಯೇ?', phonetic: 'Ee bus railway station-ge hoguttadeye?', correct: true, feedback: 'Perfect! Asking if the bus goes to the railway station.', feedback_hi: 'बिल्कुल सही! बस के रेलवे स्टेशन जाने के बारे में पूछ रहे हैं।' },
          { text: 'ಟಿಕೆಟ್ ಎಷ್ಟು?', phonetic: 'Ticket eshtu?', correct: false, feedback: 'First confirm the destination before asking the price!', feedback_hi: 'कीमत पूछने से पहले गंतव्य की पुष्टि करें!' },
          { text: 'ಇಳಿಯಿರಿ', phonetic: 'Iliyiri', correct: false, feedback: 'This means "get off" — you\'re still boarding!', feedback_hi: 'इसका अर्थ है "उतरो" — आप अभी चढ़ रहे हैं!' },
        ],
      },
      {
        id: 2,
        title: 'Buying a Ticket',
        title_hi: 'टिकट खरीदना',
        prompt: 'The conductor approaches. Ask for one ticket to Majestic.',
        prompt_hi: 'कंडक्टर आता है। मेजेस्टिक के लिए एक टिकट माँगें।',
        options: [
          { text: 'ಇನ್ನೂ ಜಾಗ ಇದೆಯೇ?', phonetic: 'Innu jaaga ideye?', correct: false, feedback: 'This asks if there\'s more space — ask for a ticket instead!', feedback_hi: 'यह पूछता है कि जगह है — इसके बजाय टिकट माँगें!' },
          { text: 'ಮೆಜೆಸ್ಟಿಕ್‌ಗೆ ಒಂದು ಟಿಕೆಟ್ ಕೊಡಿ', phonetic: 'Majestic-ge ondu ticket kodi', correct: true, feedback: 'Great! "Give me one ticket to Majestic."', feedback_hi: 'बढ़िया! "मेजेस्टिक के लिए एक टिकट दें।"' },
          { text: 'ನಮಸ್ಕಾರ', phonetic: 'Namaskaara', correct: false, feedback: 'A greeting is nice but the conductor needs to know your destination!', feedback_hi: 'अभिवादन अच्छा है लेकिन कंडक्टर को आपका गंतव्य जानना चाहिए!' },
        ],
      },
      {
        id: 3,
        title: 'Asking About the Stop',
        title_hi: 'स्टॉप के बारे में पूछना',
        prompt: 'You\'re unsure if you\'ve missed your stop. Ask the conductor.',
        prompt_hi: 'आपको यकीन नहीं है कि आपका स्टॉप निकल गया या नहीं। कंडक्टर से पूछें।',
        options: [
          { text: 'ವೇಗವಾಗಿ ಹೋಗಿ', phonetic: 'Vegavaagi hogi', correct: false, feedback: 'Telling the driver to go fast won\'t help you find your stop!', feedback_hi: 'ड्राइवर को तेज़ जाने को कहना आपका स्टॉप ढूँढने में मदद नहीं करेगा!' },
          { text: 'ಮೆಜೆಸ್ಟಿಕ್ ಬಂತೇ?', phonetic: 'Majestic bante?', correct: true, feedback: 'Correct! "Has Majestic come?" — clear and to the point.', feedback_hi: 'सही! "मेजेस्टिक आ गया?" — स्पष्ट और सटीक।' },
          { text: 'ಇಳಿಯುತ್ತೇನೆ', phonetic: 'Iliyuttene', correct: false, feedback: 'This means "I\'m getting off" — you don\'t know if it\'s the right stop yet!', feedback_hi: 'इसका अर्थ है "मैं उतर रहा हूँ" — आपको अभी पता नहीं कि यह सही स्टॉप है!' },
        ],
      },
      {
        id: 4,
        title: 'Getting Off',
        title_hi: 'उतरना',
        prompt: 'The conductor confirms your stop is next. What do you say as you get up?',
        prompt_hi: 'कंडक्टर पुष्टि करता है कि आपका स्टॉप अगला है। उठते समय क्या कहेंगे?',
        options: [
          { text: 'ಇಳಿಯುತ್ತೇನೆ, ಧನ್ಯವಾದ', phonetic: 'Iliyuttene, dhanyavaada', correct: true, feedback: 'Perfect — "I\'m getting off, thank you." Polite and clear.', feedback_hi: 'बिल्कुल सही — "मैं उतर रहा हूँ, धन्यवाद।" विनम्र और स्पष्ट।' },
          { text: 'ಇನ್ನೂ ಒಂದು ಟಿಕೆಟ್', phonetic: 'Innu ondu ticket', correct: false, feedback: 'You\'re at your stop — no need for another ticket!', feedback_hi: 'आप अपने स्टॉप पर हैं — और टिकट की ज़रूरत नहीं!' },
          { text: 'ಬೇಗ ಹೋಗಿ', phonetic: 'Bega hogi', correct: false, feedback: 'Telling the bus to go fast isn\'t quite the right farewell!', feedback_hi: 'बस को तेज़ जाने को कहना सही विदाई नहीं है!' },
        ],
      },
      {
        id: 5,
        title: 'Asking for Change',
        title_hi: 'खुल्ले माँगना',
        prompt: 'You gave ₹20 for a ₹14 ticket. Ask for your change.',
        prompt_hi: 'आपने ₹14 के टिकट के लिए ₹20 दिए। अपने खुल्ले माँगें।',
        options: [
          { text: 'ಧನ್ಯವಾದ', phonetic: 'Dhanyavaada', correct: false, feedback: 'Don\'t forget your change before you thank them!', feedback_hi: 'धन्यवाद कहने से पहले अपने खुल्ले मत भूलें!' },
          { text: 'ಚಿಲ್ಲರೆ ಕೊಡಿ', phonetic: 'Chillare kodi', correct: true, feedback: 'Exactly right! "Give me the change."', feedback_hi: 'बिल्कुल सही! "खुल्ले दो।"' },
          { text: 'ಟಿಕೆಟ್ ಎಲ್ಲಿ?', phonetic: 'Ticket elli?', correct: false, feedback: 'You already have your ticket — ask for the change!', feedback_hi: 'आपके पास पहले से टिकट है — खुल्ले माँगें!' },
        ],
      },
    ],
  },
  {
    id: 'taxi',
    title: 'Calling the Taxi',
    title_hi: 'टैक्सी बुलाना',
    kannadaTitle: 'ಟ್ಯಾಕ್ಸಿ ಕರೆ',
    subtitle: 'Call a local taxi driver, explain your location, and ask him to come quickly. Real-world Kannada communication!',
    subtitle_hi: 'एक स्थानीय टैक्सी चालक को कॉल करें, अपना स्थान बताएं और जल्दी आने को कहें। वास्तविक कन्नड़ संवाद!',
    image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&q=80',
    imageAlt: 'Taxi on Indian road',
    ctaLabel: 'Make the Call',
    ctaLabel_hi: 'कॉल करें',
    scenarios: [
      {
        id: 1,
        title: 'Introducing Yourself',
        title_hi: 'खुद का परिचय देना',
        prompt: 'The driver picks up. Greet him and say your name.',
        prompt_hi: 'ड्राइवर फोन उठाता है। उसे अभिवादन करें और अपना नाम बताएं।',
        options: [
          { text: 'ನಮಸ್ಕಾರ, ನನ್ನ ಹೆಸರು ರಾಜ್', phonetic: 'Namaskaara, nanna hesaru Raj', correct: true, feedback: 'Great start! A polite greeting followed by your name.', feedback_hi: 'बढ़िया शुरुआत! विनम्र अभिवादन के बाद आपका नाम।' },
          { text: 'ಬೇಗ ಬನ್ನಿ!', phonetic: 'Bega banni!', correct: false, feedback: 'Jumping straight to "come quickly" without greeting is a bit rude!', feedback_hi: 'अभिवादन के बिना सीधे "जल्दी आओ" कहना थोड़ा असभ्य है!' },
          { text: 'ಟ್ಯಾಕ್ಸಿ ಬೇಕು', phonetic: 'Taxi beku', correct: false, feedback: 'He already knows you want a taxi — greet him first!', feedback_hi: 'उसे पता है आपको टैक्सी चाहिए — पहले अभिवादन करें!' },
        ],
      },
      {
        id: 2,
        title: 'Telling Your Location',
        title_hi: 'अपना स्थान बताना',
        prompt: 'Tell the driver you are near the main market.',
        prompt_hi: 'ड्राइवर को बताएं कि आप मुख्य बाज़ार के पास हैं।',
        options: [
          { text: 'ನಾನು ಮುಖ್ಯ ಮಾರುಕಟ್ಟೆ ಹತ್ತಿರ ಇದ್ದೇನೆ', phonetic: 'Naanu mukhya maarukatteya hattira iddene', correct: true, feedback: 'Perfect! Clear location — "I am near the main market."', feedback_hi: 'बिल्कुल सही! स्पष्ट स्थान — "मैं मुख्य बाज़ार के पास हूँ।"' },
          { text: 'ನನಗೆ ಗೊತ್ತಿಲ್ಲ', phonetic: 'Nanage gottilla', correct: false, feedback: 'Saying "I don\'t know" won\'t help the driver find you!', feedback_hi: '"मुझे नहीं पता" कहने से ड्राइवर आपको नहीं ढूँढ पाएगा!' },
          { text: 'ಶೀಘ್ರ ಬನ್ನಿ', phonetic: 'Sheeghra banni', correct: false, feedback: 'Tell him where you are before asking him to hurry!', feedback_hi: 'जल्दी आने को कहने से पहले उसे बताएं आप कहाँ हैं!' },
        ],
      },
      {
        id: 3,
        title: 'Asking to Come Quickly',
        title_hi: 'जल्दी आने को कहना',
        prompt: 'You\'re in a hurry. Ask the driver to come quickly.',
        prompt_hi: 'आपको जल्दी है। ड्राइवर को जल्दी आने को कहें।',
        options: [
          { text: 'ನಿಧಾನವಾಗಿ ಬನ್ನಿ', phonetic: 'Nidhaanavaagi banni', correct: false, feedback: 'This means "come slowly" — the opposite of what you want!', feedback_hi: 'इसका अर्थ है "धीरे आओ" — जो आप चाहते हैं उसके विपरीत!' },
          { text: 'ಬೇಗ ಬನ್ನಿ, ದಯವಿಟ್ಟು', phonetic: 'Bega banni, dayavittu', correct: true, feedback: 'Excellent! "Please come quickly" — urgent but polite.', feedback_hi: 'शानदार! "कृपया जल्दी आएं" — जरूरी पर विनम्र।' },
          { text: 'ಇನ್ನೂ ಎಷ್ಟು ಸಮಯ?', phonetic: 'Innu eshtu samaya?', correct: false, feedback: 'Asking how much time is left is okay, but first ask him to hurry!', feedback_hi: 'कितना समय बचा पूछना ठीक है, लेकिन पहले जल्दी आने को कहें!' },
        ],
      },
      {
        id: 4,
        title: 'Confirming the Destination',
        title_hi: 'गंतव्य की पुष्टि करना',
        prompt: 'Tell the driver you need to go to the airport.',
        prompt_hi: 'ड्राइवर को बताएं कि आपको हवाई अड्डे जाना है।',
        options: [
          { text: 'ವಿಮಾನ ನಿಲ್ದಾಣಕ್ಕೆ ಹೋಗಬೇಕು', phonetic: 'Vimaana nildaanakke hoogabeeku', correct: true, feedback: 'Correct! "I need to go to the airport."', feedback_hi: 'सही! "मुझे हवाई अड्डे जाना है।"' },
          { text: 'ರೈಲ್ವೇ ಸ್ಟೇಶನ್‌ಗೆ ಹೋಗಿ', phonetic: 'Railway station-ge hogi', correct: false, feedback: 'That\'s the railway station, not the airport!', feedback_hi: 'यह रेलवे स्टेशन है, हवाई अड्डा नहीं!' },
          { text: 'ನಾನು ಮನೆಗೆ ಹೋಗುತ್ತೇನೆ', phonetic: 'Naanu manege hoguttene', correct: false, feedback: 'You\'re going to the airport, not home!', feedback_hi: 'आप हवाई अड्डे जा रहे हैं, घर नहीं!' },
        ],
      },
      {
        id: 5,
        title: 'Asking the Fare',
        title_hi: 'किराया पूछना',
        prompt: 'Ask the driver how much the fare will be.',
        prompt_hi: 'ड्राइवर से पूछें कि किराया कितना होगा।',
        options: [
          { text: 'ಎಷ್ಟು ಆಗುತ್ತದೆ?', phonetic: 'Eshtu aaguttade?', correct: true, feedback: 'Perfect — "How much will it come to?" Natural and direct.', feedback_hi: 'बिल्कुल सही — "कितना लगेगा?" स्वाभाविक और सीधा।' },
          { text: 'ಮೀಟರ್ ಹಾಕಿ', phonetic: 'Meter haaki', correct: false, feedback: 'Asking to start the meter is valid, but asking the fare first is more natural here.', feedback_hi: 'मीटर चालू करने को कहना ठीक है, लेकिन पहले किराया पूछना यहाँ अधिक स्वाभाविक है।' },
          { text: 'ಧನ್ಯವಾದ', phonetic: 'Dhanyavaada', correct: false, feedback: 'You haven\'t agreed on a price yet — don\'t thank him yet!', feedback_hi: 'आपने अभी कीमत तय नहीं की — अभी धन्यवाद मत कहें!' },
        ],
      },
      {
        id: 6,
        title: 'Arriving & Paying',
        title_hi: 'पहुँचना और भुगतान करना',
        prompt: 'You\'ve arrived. Thank the driver and say you\'ll pay now.',
        prompt_hi: 'आप पहुँच गए। ड्राइवर को धन्यवाद दें और कहें कि आप अभी भुगतान करेंगे।',
        options: [
          { text: 'ಇನ್ನೂ ಬೇಗ!', phonetic: 'Innu bega!', correct: false, feedback: 'You\'ve arrived — no need to rush anymore!', feedback_hi: 'आप पहुँच गए — अब जल्दी की ज़रूरत नहीं!' },
          { text: 'ಇಲ್ಲಿ ನಿಲ್ಲಿಸಿ', phonetic: 'Illi nillisi', correct: false, feedback: 'Telling him to stop is useful, but wrap up politely too!', feedback_hi: 'रोकने को कहना उपयोगी है, लेकिन विनम्रता से समाप्त करें!' },
          { text: 'ಧನ್ಯವಾದ, ನಾನು ಈಗ ಹಣ ಕೊಡುತ್ತೇನೆ', phonetic: 'Dhanyavaada, naanu eega hana koduttene', correct: true, feedback: 'Great! "Thank you, I\'ll pay now." Polite and complete.', feedback_hi: 'बढ़िया! "धन्यवाद, मैं अभी पैसे दूँगा।" विनम्र और पूर्ण।' },
        ],
      },
    ],
  },
];

// Legacy export — kept for backward compatibility
export const quizScenarios = allQuizSets[0].scenarios;